### PR TITLE
Update README to include webpack 2 configuration

### PR DESCRIPTION
**Pull request by CoffiDev**
Add configuration required to be compatible with webpack 2

### CODE REVIEW

**Comment by seaneking** [comment]
👍 Thanks. Not too familiar with Webpack myself - would it be worth only including the webpack 2 conf?

**Comment by CoffiDev** [comment]
Hi! I don't think so, webpack 2 is still in beta because the documentation is not ready yet, so i don't think everyone will use it since its officialy released, and also after that probably a lot of people will still use webpack 1.

**Comment by seaneking** [comment]
Okay cool, happy to include both then. There's a bunch of duped code in those blocks though, to make things more readable I think it'd be better to trim the 2nd conf snippet into something like:

```
module: {...},
plugins: [
  new webpack.LoaderOptionsPlugin({
    options: {
      stylus: {
        use: [poststylus([ 'autoprefixer', 'rucksack-css' ])]
      }
    }
  })
]
```

**Comment by CoffiDev** [comment]
I think it's fine, just notice that
`var webpack = require('webpack');`
is missing. 
Maybe it can be intuitive, but I think its better to include it just in case.

**Pull request merged**
